/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Controle;
import java.awt.Color;
import java.io.IOException;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.Timer;
import modelo.Playlist;
import util.ClassPlayer;

/**
 *
 * @author Gustavo
 */
public class TelaPlayer extends javax.swing.JFrame {
    Controle controle;
    private final Playlist playlist;
    ClassPlayer player;
    
    
    /**
     * Creates new form TelaPlayer
     * @param controle
     */
    public TelaPlayer(Controle controle) {
        initComponents();
        this.controle = controle;
        jButtonPause.setEnabled(false);
        jButtonAvancar.setEnabled(false);
        jButtonVoltar.setEnabled(false);
        this.playlist = controle.getPlaylist();
        player = new ClassPlayer(controle.buscarMusicasPlaylist(this.playlist.getIdPlaylist()),this);
        jLabelMusica.setText(player.getMusicName());
    }
    
    public void setNomeMusica(String nome){
        jLabelMusica.setText(nome);
    }
    
     public void fecharJanela(){
        controle.fecharTelaPlayer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonRepPlay = new javax.swing.JButton();
        jButtonAvancar = new javax.swing.JButton();
        jButtonPlay = new javax.swing.JButton();
        jButtonPause = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jButtonRepMus = new javax.swing.JButton();
        jLabelMusica = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAleatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player de Musicas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 0));

        jButtonRepPlay.setBackground(new java.awt.Color(204, 255, 204));
        jButtonRepPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/repetep.png"))); // NOI18N
        jButtonRepPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepPlayActionPerformed(evt);
            }
        });

        jButtonAvancar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAvancar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/passa.png"))); // NOI18N
        jButtonAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarActionPerformed(evt);
            }
        });

        jButtonPlay.setBackground(new java.awt.Color(204, 255, 204));
        jButtonPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/play.png"))); // NOI18N
        jButtonPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayActionPerformed(evt);
            }
        });

        jButtonPause.setBackground(new java.awt.Color(204, 255, 204));
        jButtonPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pause.png"))); // NOI18N
        jButtonPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPauseActionPerformed(evt);
            }
        });

        jButtonVoltar.setBackground(new java.awt.Color(204, 255, 204));
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/volta.png"))); // NOI18N
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonRepMus.setBackground(new java.awt.Color(204, 255, 204));
        jButtonRepMus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/repetem.png"))); // NOI18N
        jButtonRepMus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepMusActionPerformed(evt);
            }
        });

        jLabelMusica.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabelMusica.setForeground(new java.awt.Color(0, 255, 153));
        jLabelMusica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMusica.setText("m");
        jLabelMusica.setToolTipText("");
        jLabelMusica.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sound_audio_music_headphone_overears_earphone_icon_219964.png"))); // NOI18N
        jLabel1.setText("Musicfy");

        jButtonAleatorio.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAleatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/aleatorio.png"))); // NOI18N
        jButtonAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAleatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonRepPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRepMus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabelMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPause, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonAleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonRepPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jButtonRepMus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controle.fecharTelaPlayer();
        player.exit();
    }//GEN-LAST:event_formWindowClosed

    private void jButtonPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPauseActionPerformed
        player.pauseMusic();
        jButtonPlay.setEnabled(true);
    }//GEN-LAST:event_jButtonPauseActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        player.returnMusic();
        jLabelMusica.setText(player.getMusicName());
        jButtonPlay.setEnabled(false);
  
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarActionPerformed
        player.passMusic();
        jLabelMusica.setText(player.getMusicName());
        jButtonPlay.setEnabled(false);
    }//GEN-LAST:event_jButtonAvancarActionPerformed

    private void jButtonAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAleatorioActionPerformed
        try {
            player.aleatorio();
            jLabelMusica.setText(player.getMusicName());
            player.playMusic();
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(TelaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(TelaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAleatorioActionPerformed

    private void jButtonRepPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepPlayActionPerformed
        if(player.getRepetirPlaylist()){
            Color col = new Color(204,255,204);
            jButtonRepPlay.setBackground(col);
            player.setRepetirPlaylist(false);
        } else {
             Color col = new Color(153,255,153);
            jButtonRepPlay.setBackground(col);
            player.setRepetirPlaylist(true);
        }
    }//GEN-LAST:event_jButtonRepPlayActionPerformed

    private void jButtonRepMusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepMusActionPerformed
        if(player.getRepetirMusica()){
            Color col = new Color(204,255,204);
            jButtonRepMus.setBackground(col);
            player.setRepetirMusica(false);
        } else {
             Color col = new Color(153,255,153);
            jButtonRepMus.setBackground(col);
            player.setRepetirMusica(true);
        }
    }//GEN-LAST:event_jButtonRepMusActionPerformed

    private void jButtonPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayActionPerformed
        try {
            player.playMusic();
            jButtonPlay.setEnabled(false);
            jButtonPause.setEnabled(true);
            jButtonAvancar.setEnabled(true);
            jButtonVoltar.setEnabled(true);
        } catch (UnsupportedAudioFileException ex) {
            Logger.getLogger(TelaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (LineUnavailableException ex) {
            Logger.getLogger(TelaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPlayer.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonPlayActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAleatorio;
    private javax.swing.JButton jButtonAvancar;
    private javax.swing.JButton jButtonPause;
    private javax.swing.JButton jButtonPlay;
    private javax.swing.JButton jButtonRepMus;
    private javax.swing.JButton jButtonRepPlay;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMusica;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
