/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.Controle;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.Albun;
import modelo.Playlist;
import modelo.Usuario;

/**
 *
 * @author Gustavo
 */
public class TelaPrincipal extends javax.swing.JFrame {
    Controle controle;
    Usuario usuario = new Usuario();
    Administrador adm = new Administrador();
    List<Playlist> listPlaylists;
    /**
     * Creates new form TelaPrincipalUsuario
     */
    public TelaPrincipal(Controle controle) {
        initComponents();
        this.controle = controle;
        jMenuBar.add(jMenuPrincipal);
        jMenuBar.add(jMenuAlbuns);
        if(controle.getUsuario().getPermissao().equals("usr")){
            this.usuario = controle.getUsuario();
            jLabelImformacao.setText("Bem vindo " + usuario.getNome()+"!");
            jMenuBar.remove(jMenuAlbuns);
        } else {
            this.adm = controle.getAdiministrador();
            jLabelImformacao.setText("Bem vindo " + adm.getNome()+"!");
            
        }
        this.atualizarTabela();
        
    }
    
    public void atualizarTabela() {
        
        String titulos[] = new String[2];
        titulos[0] = "Id";
        titulos[1] = "Nome";
        int id;
        if(this.usuario.getIdUsuario()==0){
            id = this.adm.getIdUsuario();
        }else{
            id = this.usuario.getIdUsuario();
        }
        List<Playlist> playlists = controle.consultarPlaylists(id);
        this.listPlaylists = playlists;

        String dados[][] = new String[playlists.size()][2];
        for (int i = 0; i < playlists.size(); i++) {
            dados[i][0] = String.valueOf(playlists.get(i).getIdPlaylist());
            dados[i][1] = playlists.get(i).getNome();
        }

        DefaultTableModel modeloTabela = new DefaultTableModel(dados, titulos);
        jTablePlaylists.setModel(modeloTabela);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonTocarMusica = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePlaylists = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCriarPlaylist = new javax.swing.JButton();
        jLabelImformacao = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuAlbuns = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItemCadastrarMusica = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Player");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 36)); // NOI18N
        jLabel1.setText("Playlists");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jButtonTocarMusica.setBackground(new java.awt.Color(51, 51, 51));
        jButtonTocarMusica.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButtonTocarMusica.setForeground(new java.awt.Color(153, 255, 153));
        jButtonTocarMusica.setText("Tocar");
        jButtonTocarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTocarMusicaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonTocarMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jButtonEditar.setBackground(new java.awt.Color(51, 51, 51));
        jButtonEditar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButtonEditar.setForeground(new java.awt.Color(153, 255, 153));
        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jTablePlaylists.setAutoCreateRowSorter(true);
        jTablePlaylists.setBackground(new java.awt.Color(240, 240, 240));
        jTablePlaylists.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jTablePlaylists.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTablePlaylists);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 380, 230));

        jButtonExcluir.setBackground(new java.awt.Color(51, 51, 51));
        jButtonExcluir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButtonExcluir.setForeground(new java.awt.Color(153, 255, 153));
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jButtonCriarPlaylist.setBackground(new java.awt.Color(51, 51, 51));
        jButtonCriarPlaylist.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jButtonCriarPlaylist.setForeground(new java.awt.Color(153, 255, 153));
        jButtonCriarPlaylist.setText("Criar Playlist");
        jButtonCriarPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCriarPlaylistActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCriarPlaylist, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        jLabelImformacao.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabelImformacao.setText("Imformacao");
        jPanel1.add(jLabelImformacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 112, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));

        jMenuBar.setBackground(new java.awt.Color(0, 51, 0));

        jMenuPrincipal.setForeground(new java.awt.Color(153, 255, 153));
        jMenuPrincipal.setText("Menu");

        jMenuItemSobre.setForeground(new java.awt.Color(153, 255, 153));
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemSobre);

        jMenuItemSair.setForeground(new java.awt.Color(153, 255, 153));
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemSair);

        jMenuBar.add(jMenuPrincipal);

        jMenuAlbuns.setBackground(new java.awt.Color(0, 51, 0));
        jMenuAlbuns.setForeground(new java.awt.Color(153, 255, 153));
        jMenuAlbuns.setText("Cadastros");

        jMenuItem5.setBackground(new java.awt.Color(0, 51, 0));
        jMenuItem5.setForeground(new java.awt.Color(153, 255, 153));
        jMenuItem5.setText("Música");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuAlbuns.add(jMenuItem5);

        jMenuItemCadastrarMusica.setBackground(new java.awt.Color(0, 51, 0));
        jMenuItemCadastrarMusica.setForeground(new java.awt.Color(153, 255, 153));
        jMenuItemCadastrarMusica.setText("Artista");
        jMenuItemCadastrarMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarMusicaActionPerformed(evt);
            }
        });
        jMenuAlbuns.add(jMenuItemCadastrarMusica);

        jMenuItem3.setBackground(new java.awt.Color(0, 51, 0));
        jMenuItem3.setForeground(new java.awt.Color(153, 255, 153));
        jMenuItem3.setText("Albuns");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuAlbuns.add(jMenuItem3);

        jMenuItemUsuarios.setBackground(new java.awt.Color(0, 51, 0));
        jMenuItemUsuarios.setForeground(new java.awt.Color(153, 255, 153));
        jMenuItemUsuarios.setText("Usuarios");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenuAlbuns.add(jMenuItemUsuarios);

        jMenuBar.add(jMenuAlbuns);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        controle.fecharTelaPrincipalUsuario();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controle.fecharTelaPrincipalUsuario();
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        controle.abrirTelaCadastrarMusica();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItemCadastrarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarMusicaActionPerformed
        controle.abrirTelaGerenciarArtista();
    }//GEN-LAST:event_jMenuItemCadastrarMusicaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        controle.abrirTelaGerenciarAlbuns();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int id;
        if(this.usuario.getIdUsuario()==0){
            id = this.adm.getIdUsuario();
        }else{
            id = this.usuario.getIdUsuario();
        }
        controle.setPlayslist(this.listPlaylists.get(jTablePlaylists.getSelectedRow()));
        controle.setId(id);
        controle.abrirTelaGerenciarPlaylist();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonTocarMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTocarMusicaActionPerformed
        controle.setPlayslist(this.listPlaylists.get(jTablePlaylists.getSelectedRow()));
        controle.abrirTelasPlayer();
    }//GEN-LAST:event_jButtonTocarMusicaActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int i = jTablePlaylists.getSelectedRow();        
        controle.excluirPlaylist(this.listPlaylists.get(i));
        this.atualizarTabela();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCriarPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCriarPlaylistActionPerformed
        int id;
        if(this.usuario.getIdUsuario()==0){
            id = this.adm.getIdUsuario();
        }else{
            id = this.usuario.getIdUsuario();
        }
        controle.setId(id);
        controle.abrirTelaCadastrarPlaylist();
    }//GEN-LAST:event_jButtonCriarPlaylistActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        controle.abrirTelaSobre();
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        controle.abrirTelaUsuarios();
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        this.atualizarTabela();
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCriarPlaylist;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonTocarMusica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImformacao;
    private javax.swing.JMenu jMenuAlbuns;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemCadastrarMusica;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePlaylists;
    // End of variables declaration//GEN-END:variables
}
